[project]
name = "regulation-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-chroma>=0.2.3",
    "langchain-community>=0.3.22",
    "langchain-google-genai>=2.1.3",
    "langchain-openai>=0.3.14",
    "langchain-text-splitters>=0.3.8",
    "python-dotenv>=1.1.0",
    "streamlit>=1.44.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
